Change order of operations

diff --git a/.github/workflows/update-fetchgit.yml b/.github/workflows/update-fetchgit.yml
--- a/.github/workflows/update-fetchgit.yml
+++ b/.github/workflows/update-fetchgit.yml
@@ -46,6 +46,14 @@ jobs:
         with:
           ref: "${{ env.BRANCH_NAME }}"
 
+      - name: Update from master branch
+        run: |
+          if ! git pull --rebase origin master; then
+            echo "Rebase failed, merge-pulling"
+            git rebase --abort
+            git pull origin master
+          fi
+
       - name: Check for updated hashes
         run: |
           update-nix-fetchgit homedir.nix
@@ -65,15 +73,6 @@ jobs:
           # we use a single branch in parallel to ensure only one PR is active at a given time
           # if the PR has not been merged yet and new changes are detected, the existing PR will be updated accordingly
           if ! git diff --quiet --exit-code; then
-            # make sure it is up to date with master
-            git stash
-            # fall back to merge workflow if rebase fails
-            if ! git pull --rebase origin master; then
-              git rebase --abort
-              git pull --no-rebase origin master
-            fi
-            git stash pop
-
             # commit changes
             git commit -m "Update fetchGit hashes" .
 
